### PR TITLE
[FEATURE] Translation support for paginate widget

### PR DESCRIPTION
**Pull request by kdambekalns**

### CODE REVIEW

**Comment by kdambekalns** [comment]
:+1: from my side ;)

**Comment by dfeyer** [comment]
:+1: by reading (dont read I validate the translation)

**Comment by daniellienert** [comment]
:+1: by reading. All languages from translate.neos.io are present.

**Comment by aertmann** [comment]
:+1: by reading

Although this is still limiting IMO, in case I want to have something different than "next" I'd still have to overwrite the template. But anyway the view helper is pretty inflexible in general, so never use it myself..

Side note, it's not necessary to add it to all the languages is it? Crowdin will automatically do that normally right? Not currently due to the job being disabled after the GH move of course..

**Comment by kdambekalns** [comment]
No, the TYPO3.TYPO3CR.Search package has not been set up at crowdin yet. TBH I just copied all the language files from the Fluid pagination widget ;)

**Pull request merged**
